name: Generate Snake Animation

on:
  schedule:
    # Run every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: nikkvijay
          svg_out_path: dist/snake.svg

      - run: |
          git config --local user.name "nikkvijay"
          git config --local user.email "jatalenikhileshwar@gmail.com"
          git add -A
          git commit -m "Updated snake animation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
